<%@ Page Title="" Language="C#" MasterPageFile="~/Assets/Templates/Empty/Empty.Master" AutoEventWireup="true" CodeBehind="Terms.aspx.cs" Inherits="XMlogin.Terms" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
	<div class="container-fluid">
		<!-- Profile Information -------------------------------------------------------------------------->

		<h2>uStore Terms of Use</h2>
		<p>&nbsp;</p>

		<p>By accessing and/or using the Dominion Blue website (the "Site"), You accept, without limitation or qualifications, the following Terms of Use:</p>

		<ol>
			<li>Dominion Blue maintains this Site for Your personal use, entertainment, information, education, and communication. Dominion Blue grants You the permission to use and view the Site subject to these Terms of Use.</li>
			<li>You may not modify, copy, transmit, display, reproduce, publish, license, create derivative works from, transfer, or sell any information, materials, software, designs, drawings, content, products or services from the Site (together "Content") in any form without Dominion Blue's prior written permission. You may print out a copy or download Content solely for Your personal use. In doing so, You may not remove or alter, or cause to be removed or altered, any copyright, trademark, trade name, service mark, or any other proprietary notice or legend appearing on any of the Content.</li>
			<li>Dominion Blue has the right at any time to change or discontinue any aspect or feature of the Site.</li>
			<li>You may use the Site for lawful purposes only. You may not post or transmit through the Site any material which violates or infringes in any way upon the rights of others, which is unlawful, threatening, abusive, defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane or otherwise objectionable, which encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law. Dominion Blue will fully cooperate with any law enforcement authorities or court order requesting or directing Dominion Blue to disclose the identity of anyone posting such information or materials.</li>
			<li>The trademarks, logos, and service marks (collectively the "Trademarks") displayed on the Site are registered and unregistered Trademarks of Dominion Blue and others. Nothing contained on the Site should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Trademark displayed on the Site without the written permission of Dominion Blue or such party that may own the Trademark. Your use of the Trademarks displayed on the Site, or any other content on the Site, except as provided in these Terms of Use, are strictly prohibited. Dominion Blue will aggressively enforce its intellectual property rights to the fullest extent of the law, including seeking criminal prosecution.</li>
			<li>Your use of and browsing in the Site are at Your sole risk. Neither Dominion Blue, any of its agencies, nor any other party involved in creating, producing or delivering the Site is liable to You for any direct, incidental, consequential, indirect, special or punitive damages arising out of Your use of or access to the Site. THE SITE IS PROVIDED TO YOU "AS IS" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Some jurisdictions may not allow the exclusion of certain implied warranties, so some of the above exclusions may not apply to You.</li>
			<li>Dominion Blue DOES NOT WARRANT THAT THE SITE OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE; NOR DOES Dominion Blue MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SITE, OR AS TO THE ACCURACY, RELIABILITY OR CONTENTS OF ANY INFORMATION, SERVICE, OR PRODUCT PROVIDED THROUGH THE SITE.</li>
			<li>Dominion Blue does not assume any responsibility or risk for Your use of the Site. Dominion Blue does not guarantee or warrant that files available for downloading from the Internet will be free of infection of viruses, worms, Trojan horses or other code that manifest contaminating or destructive properties. You are responsible for implementing sufficient procedures and checkpoints to satisfy Your particular requirements for accuracy of data input and output, and for maintaining a means external to the Site for the reconstruction of any lost data.</li>
			<li>Dominion Blue is not undertaking to perform construction, architectural, engineering, accounting, legal or other professional advice or services. The drawings and plans (the "Plans") offered for sale on this Site are offered by their respective owners or licensees only. Dominion Blue PROVIDES THE PLANS WITHOUT WARRANTEES OF ANY KIND, INCLUDING WITHOUT LIMITATION, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE AND DISCLAIMS ANY LIABILITY RELATING TO THE ACCURACY OR INACCURACY, RELIABILITY, OR CONTENTS OF THE PLANS.</li>
			<li>You will indemnify and hold Dominion Blue, its licensors, content providers, service providers and contractors (the "Indemnified Parties") harmless from any breach of these Terms of Use by You, including any use of Content other than as expressly authorized in these Terms of Use. You agree that the Indemnified Parties will have no liability in connection with any such breach or unauthorized use, and agree to indemnify any and all resulting loss, damages, judgments, awards, costs, expenses, and attorneys' fees of the Indemnified Parties in connection therewith. You will also indemnify and hold the Indemnified Parties harmless from and against any claims brought by third parties arising out of Your use of the information accessed from the Site.</li>
			<li>These Terms of Use will be governed by the law of the Province of British Columbia, without regard to its choice of law provisions. Any legal action, suit or proceeding brought by it in any way arising out of these Terms of Use must be brought solely and exclusively in the federal or provincial courts of the Province of British Columbia located in Vancouver, BC. If any provision of this agreement is held by a court of competent jurisdiction to be illegal, invalid, or unenforceable, the remaining provisions shall remain in full force and effect.</li>
			<li>Dominion Blue may at any time revise these Terms of Use by updating this posting. You are bound to any such revisions and should therefore periodically visit this page to review the then current Terms of Use.</li>
		</ol>
	</div>

	<asp:Button ID="Button_Agree" runat="server" Text="I Agree With Terms" OnClick="Button_Agree_Click" />
</asp:Content>