//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMlogin.WSAPI_AddressWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="uStoreWSAPI", ConfigurationName="WSAPI_AddressWS.AddressWSSoap")]
    public interface AddressWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/AddAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReturnObject))]
        int AddAddress(string username, string password, XMlogin.WSAPI_AddressWS.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/AddAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAddressAsync(string username, string password, XMlogin.WSAPI_AddressWS.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/UpdateAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReturnObject))]
        void UpdateAddress(string username, string password, XMlogin.WSAPI_AddressWS.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/UpdateAddress", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateAddressAsync(string username, string password, XMlogin.WSAPI_AddressWS.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/GetAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReturnObject))]
        XMlogin.WSAPI_AddressWS.Address GetAddress(string username, string password, int addressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/GetAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<XMlogin.WSAPI_AddressWS.Address> GetAddressAsync(string username, string password, int addressId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/GetAddressListByCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReturnObject))]
        XMlogin.WSAPI_AddressWS.Address[] GetAddressListByCustomer(string username, string password, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/GetAddressListByCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<XMlogin.WSAPI_AddressWS.Address[]> GetAddressListByCustomerAsync(string username, string password, int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/GetAddressListByUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReturnObject))]
        XMlogin.WSAPI_AddressWS.Address[] GetAddressListByUser(string username, string password, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uStoreWSAPI/GetAddressListByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<XMlogin.WSAPI_AddressWS.Address[]> GetAddressListByUserAsync(string username, string password, int userId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uStoreWSAPI")]
    public partial class Address : ReturnObject {
        
        private int addressIDField;
        
        private int addressTypeIDField;
        
        private string displayNameField;
        
        private string personNameField;
        
        private string companyField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string zipField;
        
        private string phoneField;
        
        private string faxField;
        
        private int stateIDField;
        
        private int countryIDField;
        
        private int customerIDField;
        
        private int userIDField;
        
        private string addressReferenceField;
        
        private string taxRegistrationField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AddressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
                this.RaisePropertyChanged("AddressID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AddressTypeID {
            get {
                return this.addressTypeIDField;
            }
            set {
                this.addressTypeIDField = value;
                this.RaisePropertyChanged("AddressTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PersonName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
                this.RaisePropertyChanged("PersonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int StateID {
            get {
                return this.stateIDField;
            }
            set {
                this.stateIDField = value;
                this.RaisePropertyChanged("StateID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
                this.RaisePropertyChanged("CountryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AddressReference {
            get {
                return this.addressReferenceField;
            }
            set {
                this.addressReferenceField = value;
                this.RaisePropertyChanged("AddressReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TaxRegistration {
            get {
                return this.taxRegistrationField;
            }
            set {
                this.taxRegistrationField = value;
                this.RaisePropertyChanged("TaxRegistration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uStoreWSAPI")]
    public abstract partial class ReturnObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressWSSoapChannel : XMlogin.WSAPI_AddressWS.AddressWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressWSSoapClient : System.ServiceModel.ClientBase<XMlogin.WSAPI_AddressWS.AddressWSSoap>, XMlogin.WSAPI_AddressWS.AddressWSSoap {
        
        public AddressWSSoapClient() {
        }
        
        public AddressWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddAddress(string username, string password, XMlogin.WSAPI_AddressWS.Address address) {
            return base.Channel.AddAddress(username, password, address);
        }
        
        public System.Threading.Tasks.Task<int> AddAddressAsync(string username, string password, XMlogin.WSAPI_AddressWS.Address address) {
            return base.Channel.AddAddressAsync(username, password, address);
        }
        
        public void UpdateAddress(string username, string password, XMlogin.WSAPI_AddressWS.Address address) {
            base.Channel.UpdateAddress(username, password, address);
        }
        
        public System.Threading.Tasks.Task UpdateAddressAsync(string username, string password, XMlogin.WSAPI_AddressWS.Address address) {
            return base.Channel.UpdateAddressAsync(username, password, address);
        }
        
        public XMlogin.WSAPI_AddressWS.Address GetAddress(string username, string password, int addressId) {
            return base.Channel.GetAddress(username, password, addressId);
        }
        
        public System.Threading.Tasks.Task<XMlogin.WSAPI_AddressWS.Address> GetAddressAsync(string username, string password, int addressId) {
            return base.Channel.GetAddressAsync(username, password, addressId);
        }
        
        public XMlogin.WSAPI_AddressWS.Address[] GetAddressListByCustomer(string username, string password, int customerId) {
            return base.Channel.GetAddressListByCustomer(username, password, customerId);
        }
        
        public System.Threading.Tasks.Task<XMlogin.WSAPI_AddressWS.Address[]> GetAddressListByCustomerAsync(string username, string password, int customerId) {
            return base.Channel.GetAddressListByCustomerAsync(username, password, customerId);
        }
        
        public XMlogin.WSAPI_AddressWS.Address[] GetAddressListByUser(string username, string password, int userId) {
            return base.Channel.GetAddressListByUser(username, password, userId);
        }
        
        public System.Threading.Tasks.Task<XMlogin.WSAPI_AddressWS.Address[]> GetAddressListByUserAsync(string username, string password, int userId) {
            return base.Channel.GetAddressListByUserAsync(username, password, userId);
        }
    }
}
